//! Build script to validate datasets.toml against DatasetId enum.
//!
//! This build script reads datasets.toml and generates compile-time validation
//! that ensures the TOML and Rust enum stay in sync.
//!
//! Note: We don't generate the enum itself because:
//! 1. The enum variants need to be stable for serialization compatibility
//! 2. IDE tooling works better with explicit Rust definitions
//! 3. The enum has associated methods that need manual implementation
//!
//! Instead, we generate a validation module that fails compilation if
//! TOML and enum are out of sync.

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to rerun if datasets.toml changes
    println!("cargo:rerun-if-changed=../datasets.toml");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("dataset_validation.rs");

    // Read datasets.toml
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let toml_path = Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .join("datasets.toml");

    if !toml_path.exists() {
        // Generate empty validation if TOML doesn't exist
        fs::write(
            &dest_path,
            "// datasets.toml not found - skipping validation",
        )
        .unwrap();
        return;
    }

    let toml_content = fs::read_to_string(&toml_path).expect("Failed to read datasets.toml");

    // Parse TOML and extract dataset keys
    let toml: toml::Value = toml_content.parse().expect("Invalid TOML");

    let mut dataset_keys: HashSet<String> = HashSet::new();
    let mut rust_variants: HashSet<String> = HashSet::new();

    if let Some(toml::Value::Table(root)) = Some(&toml) {
        if let Some(toml::Value::Table(datasets)) = root.get("datasets") {
            for (key, value) in datasets {
                dataset_keys.insert(key.clone());

                // Extract rust_variant if present
                if let toml::Value::Table(entry) = value {
                    if let Some(toml::Value::String(variant)) = entry.get("rust_variant") {
                        rust_variants.insert(variant.clone());
                    }
                }
            }
        }
    }

    // Generate validation code
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs - DO NOT EDIT\n");
    code.push_str("// This module validates that datasets.toml matches DatasetId enum\n\n");

    code.push_str("/// Number of datasets defined in datasets.toml\n");
    code.push_str(&format!(
        "pub const TOML_DATASET_COUNT: usize = {};\n\n",
        dataset_keys.len()
    ));

    code.push_str("/// Dataset keys from datasets.toml (for runtime validation)\n");
    code.push_str("pub const TOML_DATASET_KEYS: &[&str] = &[\n");
    for key in dataset_keys.iter() {
        // Skip aliases
        if let Some(toml::Value::Table(datasets)) = toml.get("datasets") {
            if let Some(toml::Value::Table(entry)) = datasets.get(key) {
                if entry.get("alias_of").is_some() {
                    continue;
                }
            }
        }
        code.push_str(&format!("    \"{}\",\n", key));
    }
    code.push_str("];\n\n");

    code.push_str("/// Rust variants from datasets.toml (for compile-time validation)\n");
    code.push_str("pub const TOML_RUST_VARIANTS: &[&str] = &[\n");
    for variant in rust_variants.iter() {
        code.push_str(&format!("    \"{}\",\n", variant));
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).expect("Failed to write validation code");
}
