//! Pseudonymized audit event shapes + persistent sinks.

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use std::fs::OpenOptions;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use time::macros::format_description;
use time::OffsetDateTime;

type HmacSha256 = Hmac<Sha256>;

/// Safe request audit metadata. Never includes cleartext prompts, rehydrated
/// answers, or vault contents.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct AuditEvent {
    /// Request id generated by the gateway or caller.
    pub request_id: String,
    /// Provider profile used for routing.
    pub provider_profile: String,
    /// Count of replaced entities.
    pub entity_count: usize,
    /// Count of fresh PII redactions on response.
    pub fresh_pii_redacted: usize,
}

/// Audit sink abstraction.
pub trait AuditSink: Send + Sync {
    /// Record a safe audit event.
    fn record(&self, event: AuditEvent);
}

/// No-op sink — for tests only.
#[derive(Debug, Default)]
pub struct NoopAuditSink;

impl AuditSink for NoopAuditSink {
    fn record(&self, _event: AuditEvent) {}
}

/// Persistent tamper-evident JSONL sink.
///
/// Layout under `dir`:
/// - `YYYY-MM-DD.jsonl` — one event per line, with `prev_hash` / `this_hash`
/// - `YYYY-MM-DD.sig` — HMAC-SHA256(key, last_this_hash) in hex
///
/// Chain head is 64 hex zeros at the start of each UTC day; subsequent
/// lines chain via `this_hash = sha256(prev_hash_bytes || event_json)`.
/// The `.sig` file is rewritten on every event with the HMAC of the
/// latest `this_hash` — a verifier can replay the chain off-line and
/// compare against the signature.
pub struct JsonlAuditSink {
    dir: PathBuf,
    hmac_key: [u8; 32],
    state: Mutex<DailyState>,
}

struct DailyState {
    day: String,
    chain_head: String,
}

impl JsonlAuditSink {
    /// Initialise the sink. If the dir doesn't exist it's created. If
    /// today's JSONL already has lines, the chain head is recovered from
    /// the last line so chaining survives restarts.
    ///
    /// # Errors
    /// Returns the underlying I/O error if `dir` cannot be created or
    /// today's JSONL cannot be read.
    pub fn new(dir: impl Into<PathBuf>, hmac_key: [u8; 32]) -> std::io::Result<Self> {
        let dir = dir.into();
        std::fs::create_dir_all(&dir)?;
        let day = current_day();
        let chain_head = read_last_chain_head(&dir, &day)?;
        Ok(Self {
            dir,
            hmac_key,
            state: Mutex::new(DailyState { day, chain_head }),
        })
    }

    fn write_line(&self, event: &AuditEvent) -> std::io::Result<()> {
        let today = current_day();
        let mut state = self
            .state
            .lock()
            .map_err(|_| std::io::Error::other("audit mutex poisoned"))?;
        if state.day != today {
            state.day = today.clone();
            state.chain_head = "0".repeat(64);
        }
        let prev = state.chain_head.clone();
        // Canonical form: round-trip through serde_json::Value so the
        // hashed bytes are key-sorted (serde_json::Map is BTreeMap-backed
        // when the `preserve_order` feature is off, which is the default).
        // This is what makes the chain verifiable off-line by a third
        // party who only sees the JSONL file.
        let event_value = serde_json::to_value(event)
            .map_err(|e| std::io::Error::other(format!("serialize: {e}")))?;
        let event_bytes = serde_json::to_vec(&event_value)
            .map_err(|e| std::io::Error::other(format!("canonicalize: {e}")))?;
        let mut hasher = Sha256::new();
        hasher.update(hex::decode(&prev).unwrap_or_default());
        hasher.update(&event_bytes);
        let this_hash = hex::encode(hasher.finalize());

        let line = serde_json::json!({
            "ts": OffsetDateTime::now_utc()
                .format(&time::format_description::well_known::Rfc3339)
                .unwrap_or_default(),
            "event": event,
            "prev_hash": prev,
            "this_hash": this_hash,
        });
        let mut serialised = serde_json::to_vec(&line)
            .map_err(|e| std::io::Error::other(format!("serialize line: {e}")))?;
        serialised.push(b'\n');

        let jsonl_path = self.dir.join(format!("{}.jsonl", state.day));
        let mut f = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&jsonl_path)?;
        f.write_all(&serialised)?;
        f.sync_data()?;

        // Update sig file with HMAC of the latest this_hash.
        let mut mac = HmacSha256::new_from_slice(&self.hmac_key)
            .map_err(|e| std::io::Error::other(format!("hmac init: {e}")))?;
        mac.update(this_hash.as_bytes());
        let sig = hex::encode(mac.finalize().into_bytes());
        let sig_path = self.dir.join(format!("{}.sig", state.day));
        std::fs::write(&sig_path, sig)?;

        state.chain_head = this_hash;
        Ok(())
    }
}

impl AuditSink for JsonlAuditSink {
    fn record(&self, event: AuditEvent) {
        // Audit must NEVER panic the request path. Log + drop on error.
        if let Err(e) = self.write_line(&event) {
            tracing::error!("audit write failed: {e}");
        }
    }
}

fn current_day() -> String {
    OffsetDateTime::now_utc()
        .format(&format_description!("[year]-[month]-[day]"))
        .expect("static format")
}

fn read_last_chain_head(dir: &Path, day: &str) -> std::io::Result<String> {
    let path = dir.join(format!("{day}.jsonl"));
    let f = match OpenOptions::new().read(true).open(&path) {
        Ok(f) => f,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok("0".repeat(64));
        }
        Err(e) => return Err(e),
    };
    let mut last: Option<String> = None;
    for line in BufReader::new(f).lines() {
        let line = line?;
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&line) {
            if let Some(h) = v.get("this_hash").and_then(|x| x.as_str()) {
                last = Some(h.to_string());
            }
        }
    }
    Ok(last.unwrap_or_else(|| "0".repeat(64)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn ev(id: &str) -> AuditEvent {
        AuditEvent {
            request_id: id.to_string(),
            provider_profile: "test".to_string(),
            entity_count: 0,
            fresh_pii_redacted: 0,
        }
    }

    #[test]
    fn jsonl_sink_appends_line_and_chains_hashes() {
        let dir = TempDir::new().unwrap();
        let key = [42u8; 32];
        let sink = JsonlAuditSink::new(dir.path(), key).unwrap();
        sink.record(ev("r1"));
        sink.record(ev("r2"));

        let today = current_day();
        let path = dir.path().join(format!("{today}.jsonl"));
        let body = std::fs::read_to_string(&path).unwrap();
        let lines: Vec<&str> = body.lines().collect();
        assert_eq!(lines.len(), 2);

        let l1: serde_json::Value = serde_json::from_str(lines[0]).unwrap();
        let l2: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
        assert_eq!(l1["prev_hash"].as_str().unwrap(), "0".repeat(64));
        assert_eq!(
            l2["prev_hash"].as_str().unwrap(),
            l1["this_hash"].as_str().unwrap()
        );

        let sig_path = dir.path().join(format!("{today}.sig"));
        let sig_hex = std::fs::read_to_string(&sig_path).unwrap();
        assert_eq!(sig_hex.trim().len(), 64);
    }

    #[test]
    fn jsonl_sink_recovers_chain_head_across_restart() {
        let dir = TempDir::new().unwrap();
        let key = [42u8; 32];
        {
            let s = JsonlAuditSink::new(dir.path(), key).unwrap();
            s.record(ev("r1"));
        }
        let s = JsonlAuditSink::new(dir.path(), key).unwrap();
        s.record(ev("r2"));

        let today = current_day();
        let body =
            std::fs::read_to_string(dir.path().join(format!("{today}.jsonl"))).unwrap();
        let lines: Vec<&str> = body.lines().collect();
        let l1: serde_json::Value = serde_json::from_str(lines[0]).unwrap();
        let l2: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
        assert_eq!(l2["prev_hash"], l1["this_hash"]);
    }
}
