//! Pseudonymized audit event shapes.

use serde::Serialize;

/// Safe request audit metadata. Never includes cleartext prompts, rehydrated
/// answers, or vault contents.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct AuditEvent {
    /// Request id generated by the gateway or caller.
    pub request_id: String,
    /// Provider profile used for routing.
    pub provider_profile: String,
    /// Count of replaced entities.
    pub entity_count: usize,
    /// Count of fresh PII redactions on response.
    pub fresh_pii_redacted: usize,
}

/// Audit sink abstraction.
pub trait AuditSink: Send + Sync {
    /// Record a safe audit event.
    fn record(&self, event: AuditEvent);
}

/// No-op audit sink used until persistent audit lands after v0.3.
#[derive(Debug, Default)]
pub struct NoopAuditSink;

impl AuditSink for NoopAuditSink {
    fn record(&self, _event: AuditEvent) {}
}
