// Auto-generated s3_path additions
// Copy these into the appropriate dataset blocks in dataset_registry.rs

// ACE05RE: s3_path: "datasets/ace2005.json",
// ACE2005: s3_path: "datasets/ace2005.json",
// ACE2005Arabic: s3_path: "datasets/ace2005.json",
// AIDA: s3_path: "datasets/aida.conll",
// AIDACoNLL: s3_path: "datasets/aida.conll",
// ASN: s3_path: "datasets/americasnli.json",
// AerospaceNERDataset: s3_path: "datasets/e_ner.csv",
// AkkadianUD: s3_path: "datasets/akkadian_ud.conllu",
// AmericasNLI: s3_path: "datasets/americasnli.json",
// AnatEM: s3_path: "datasets/anat_em.json",
// AncientGreekUD: s3_path: "datasets/ancientgreekud.conllu",
// AncientHebrewUD: s3_path: "datasets/ancient_hebrew_ud.conllu",
// AnnoCTR: s3_path: "datasets/annoctr_train.bio",
// ArrauGenia: s3_path: "datasets/genia.json",
// AstroNER: s3_path: "datasets/astro_ner_sample.conll",
// AutomotiveNER: s3_path: "datasets/e_ner.csv",
// BBQ: s3_path: "datasets/b_b_q.json",
// BC2GM: s3_path: "datasets/bc2gm.conll",
// BC2GMFull: s3_path: "datasets/bc2gm_full.conll",
// BC4CHEMD: s3_path: "datasets/bc4chemd.conll",
// BasqueNER: s3_path: "datasets/e_ner.csv",
// BioMNER: s3_path: "datasets/biomner.conll",
// BioRED: s3_path: "datasets/biored_dev.json",
// BoardGameNER: s3_path: "datasets/e_ner.csv",
// BoldBias: s3_path: "datasets/bold_bias.txt",
// BroadTwitterCorpus: s3_path: "datasets/broad_twitter.conll",
// CRAFT: s3_path: "datasets/craft.conll",
// CRAFTCoref: s3_path: "datasets/craft.conll",
// CRAFTCorpusCoref: s3_path: "datasets/craft.conll",
// CharacterCodex: s3_path: "datasets/charactercodex.json",
// CherokeeNER: s3_path: "datasets/e_ner.csv",
// ClassicalChineseUD: s3_path: "datasets/classical_chinese_ud.conllu",
// CoNLL2002: s3_path: "datasets/conll2002.conll",
// CoNLL2002Dutch: s3_path: "datasets/conll2002.conll",
// CoNLL2002Spanish: s3_path: "datasets/conll2002.conll",
// CopticUD: s3_path: "datasets/coptic_ud.conllu",
// CovEReD: s3_path: "datasets/covered.json",
// CropDiseaseNER: s3_path: "datasets/e_ner.csv",
// CrossNER: s3_path: "datasets/crossner_politics.txt",
// CrowSPairs: s3_path: "datasets/crow_s_pairs.txt",
// DocRED: s3_path: "datasets/doc_r_e_d.json",
// Dothraki: s3_path: "datasets/dothraki.txt",
// ECBPlus: s3_path: "datasets/e_c_b_plus.csv",
// ECBPlusMeta: s3_path: "datasets/e_c_b_plus.csv",
// ENER: s3_path: "datasets/e_ner.csv",
// ENERSec: s3_path: "datasets/ener_sec.csv",
// ENer: s3_path: "datasets/e_ner.csv",
// EnergyNER: s3_path: "datasets/e_ner.csv",
// EsperantoUD: s3_path: "datasets/esperanto_ud.conllu",
// FINER: s3_path: "datasets/finer.rar",
// FINERFood: s3_path: "datasets/finer.rar",
// FabNER: s3_path: "datasets/fabner.conll",
// FewNERD: s3_path: "datasets/fewnerd_dev.txt",
// FewRel: s3_path: "datasets/few_rel.json",
// FiNER139: s3_path: "datasets/finer.rar",
// FinNER: s3_path: "datasets/finner.conll",
// FinanceNER: s3_path: "datasets/e_ner.csv",
// FragranceNER: s3_path: "datasets/e_ner.csv",
// GAP: s3_path: "datasets/g_a_p.tsv",
// GENIA: s3_path: "datasets/genia.json",
// GENIANested: s3_path: "datasets/genia_nested.iob2",
// GICoref: s3_path: "datasets/gicoref.conll",
// GNERGeoscience: s3_path: "datasets/legner.conll",
// GUM: s3_path: "datasets/gum_gentle_dictionary_next.conll",
// GermEval2014: s3_path: "datasets/germeval2014.conll",
// GoogleRE: s3_path: "datasets/googlere_dev.json",
// GothicUD: s3_path: "datasets/gothic_ud.conllu",
// HAREM: s3_path: "datasets/harem.conll",
// HighValyrian: s3_path: "datasets/high_valyrian.txt",
// HistoricalChineseNER: s3_path: "datasets/e_ner.csv",
// HittiteUD: s3_path: "datasets/hittite_ud.conllu",
// InsuranceNER: s3_path: "datasets/e_ner.csv",
// Interslavic: s3_path: "datasets/interslavic.txt",
// JNLPBA: s3_path: "datasets/jnlpba.conll",
// KLUENER: s3_path: "datasets/e_ner.csv",
// Klingon: s3_path: "datasets/klingon.txt",
// KlingonEffectLID: s3_path: "datasets/klingon.txt",
// LatinITTB: s3_path: "datasets/latin_ittb.conllu",
// LatinPROIEL: s3_path: "datasets/latin_proiel.conllu",
// LatinUD: s3_path: "datasets/latin_u_d.conllu",
// LeNERBr: s3_path: "datasets/e_ner.csv",
// LegNER: s3_path: "datasets/legner.conll",
// LegalNER: s3_path: "datasets/legalner.conll",
// LexGLUENER: s3_path: "datasets/e_ner.csv",
// LitBank: s3_path: "datasets/lit_bank.txt",
// Lojban: s3_path: "datasets/lojban.tsv",
// LojbanTatoeba: s3_path: "datasets/lojban.tsv",
// MGAP: s3_path: "datasets/g_a_p.tsv",
// MSNER: s3_path: "datasets/msner.json",
// MUC6: s3_path: "datasets/muc6.conll",
// MUC7: s3_path: "datasets/muc7.conll",
// MaritimeNER: s3_path: "datasets/e_ner.csv",
// MasakhaNER: s3_path: "datasets/masakha_n_e_r.txt",
// MasakhaNER2: s3_path: "datasets/masakha_n_e_r.txt",
// MitMovie: s3_path: "datasets/mit_movie.bio",
// MitRestaurant: s3_path: "datasets/mit_restaurant.bio",
// MixRED: s3_path: "datasets/mixred.json",
// MuDoCo: s3_path: "datasets/mu_do_co.json",
// MultiCoNER: s3_path: "datasets/multiconer_en.conll",
// MultiNERD: s3_path: "datasets/multi_n_e_r_d.json",
// NCBIDisease: s3_path: "datasets/ncbidisease.txt",
// NCHLTIsiZulu: s3_path: "datasets/uner.json",
// NCHLTisiNdebele: s3_path: "datasets/e_ner.csv",
// NNE: s3_path: "datasets/wikiann_en.jsonl",
// NYTFB: s3_path: "datasets/nytfb_dev.json",
// Navi: s3_path: "datasets/navi.txt",
// NoiseBench: s3_path: "datasets/noisebench_distant.traindev",
// OldChurchSlavonicUD: s3_path: "datasets/old_church_slavonic_ud.conllu",
// OldEnglishUD: s3_path: "datasets/old_english_ud.conllu",
// OldNorseUD: s3_path: "datasets/old_norse_ud.conllu",
// OntoNotes50: s3_path: "datasets/ontonotes50.conll",
// OntoNotesSample: s3_path: "datasets/ontonotessample.txt",
// PIIMasking200k: s3_path: "datasets/pii_masking.json",
// PileNERType: s3_path: "datasets/e_ner.csv",
// PreCo: s3_path: "datasets/preco_dev.json",
// Quenya: s3_path: "datasets/quenya.txt",
// QxoRef: s3_path: "datasets/qxoref.conll",
// ReTACRED: s3_path: "datasets/re_t_a_c_r_e_d.json",
// RealEstateNER: s3_path: "datasets/e_ner.csv",
// RealToxicityPrompts: s3_path: "datasets/real_toxicity_prompts.txt",
// RecipeNER: s3_path: "datasets/e_ner.csv",
// ResumeNER: s3_path: "datasets/e_ner.csv",
// S800: s3_path: "datasets/s800.tar.gz",
// SanskritUD: s3_path: "datasets/sanskrit_ud.conllu",
// SciCo: s3_path: "datasets/scico_data.tar",
// SciER: s3_path: "datasets/scier.jsonl",
// SciERC: s3_path: "datasets/scierc_ner.json",
// SciERCNER: s3_path: "datasets/scierc_ner.json",
// SemEval2010Task8: s3_path: "datasets/semeval2010_task8.json",
// SemEval2013Task91: s3_path: "datasets/semeval2013_task91.conll",
// SportsNERGeneral: s3_path: "datasets/e_ner.csv",
// StereoSet: s3_path: "datasets/stereo_set.txt",
// TACKBP: s3_path: "datasets/tackbp.json",
// TACRED: s3_path: "datasets/retacred_dev.json",
// TaggedPBCKlingon: s3_path: "datasets/klingon.txt",
// TemDocRED: s3_path: "datasets/doc_r_e_d.json",
// TokiPona: s3_path: "datasets/toki_pona.txt",
// TokiPonaCorpus: s3_path: "datasets/toki_pona.txt",
// TurkuNER: s3_path: "datasets/uner.json",
// TweetNER7: s3_path: "datasets/tweetner7.conll",
// TwiConv: s3_path: "datasets/twi_conv.txt",
// UDEsperantoCairo: s3_path: "datasets/u_d_esperanto_cairo.conllu",
// UNER: s3_path: "datasets/uner.json",
// UniversalNER: s3_path: "datasets/universalner_en.conllu",
// UniversalNERBench: s3_path: "datasets/universalner_bench.json",
// WEBNLG: s3_path: "datasets/webnlg_dev.json",
// WIESP2022NER: s3_path: "datasets/wiesp2022ner.json",
// WaterResourceNER: s3_path: "datasets/e_ner.csv",
// WikiANN: s3_path: "datasets/wiki_ann.json",
// WikiCoref: s3_path: "datasets/wikicoref.tsv",
// WikiNeural: s3_path: "datasets/wikineural_en.conll",
// WineNER: s3_path: "datasets/e_ner.csv",
// WinoBias: s3_path: "datasets/wino_bias.txt",
// WinoQueer: s3_path: "datasets/wino_queer.csv",

// Auto-generated alt_sources additions (HuggingFace URLs)

// AfriQA: add "https://huggingface.co/datasets/masakhane/afriqa" to alt_sources
// AfriSenti: add "https://huggingface.co/datasets/shmuhammad/AfriSenti-twitter-sentiment" to alt_sources
// AnatEM: add "https://huggingface.co/datasets/disi-unibo-nlp/AnatEM" to alt_sources
// BC2GM: add "https://huggingface.co/datasets/bigbio/bc2gm_corpus" to alt_sources
// BC4CHEMD: add "https://huggingface.co/datasets/bigbio/bc4chemd" to alt_sources
// BC5CDR: add "https://huggingface.co/datasets/tner/bc5cdr" to alt_sources
// BookCorefSplit: add "https://huggingface.co/datasets/sapienzanlp/bookcoref" to alt_sources
// BroadTwitterCorpus: add "https://huggingface.co/datasets/tner/btc" to alt_sources
// CrossNER: add "https://huggingface.co/datasets/DFKI-SLT/cross_ner" to alt_sources
// DocRED: add "https://huggingface.co/datasets/docred" to alt_sources
// FabNER: add "https://huggingface.co/datasets/DFKI-SLT/fabner" to alt_sources
// FewNERD: add "https://huggingface.co/datasets/DFKI-SLT/few-nerd" to alt_sources
// FewRel: add "https://huggingface.co/datasets/few_rel" to alt_sources
// GAP: add "https://huggingface.co/datasets/google-gap-coreference/gap" to alt_sources
// GENIA: add "https://huggingface.co/datasets/chufangao/GENIA-NER" to alt_sources
// KLUENER: add "https://huggingface.co/datasets/klue" to alt_sources
// MasakhaNER: add "https://huggingface.co/datasets/masakhane/masakhaner" to alt_sources
// MasakhaNER2: add "https://huggingface.co/datasets/masakhane/masakhaner2" to alt_sources
// MasakhaNEWS: add "https://huggingface.co/datasets/masakhane/masakhanews" to alt_sources
// MasakhaPOS: add "https://huggingface.co/datasets/masakhane/masakhane-pos" to alt_sources
// MultiNERD: add "https://huggingface.co/datasets/Babelscape/multinerd" to alt_sources
// NCBIDisease: add "https://huggingface.co/datasets/ncbi_disease" to alt_sources
// PileNERType: add "https://huggingface.co/datasets/Universal-NER/Pile-NER-type" to alt_sources
// RONEC: add "https://huggingface.co/datasets/ronec" to alt_sources
// TLUnifiedNER: add "https://huggingface.co/datasets/ljvmiranda921/tlunified-ner" to alt_sources
// TweetNER7: add "https://huggingface.co/datasets/tner/tweetner7" to alt_sources
// WIESP2022NER: add "https://huggingface.co/datasets/adsabs/WIESP2022-NER" to alt_sources
// WikiANN: add "https://huggingface.co/datasets/wikiann" to alt_sources
// WikiNeural: add "https://huggingface.co/datasets/Babelscape/wikineural" to alt_sources
// Wnut17: add "https://huggingface.co/datasets/leondz/wnut_17" to alt_sources